using System;
using Helpers;

namespace Problems {
    /*
    Even Fibonacci numbers
    Problem 2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    */
    public class Problem2 : AProblem {
        
        public override Int64? CorrectAnswer { get { return 4613732;}}
        public override Int64 Solve(){
            var sum = 0;
            var a = 1;
            var b = 2;
            while (b < 4*1000*1000){
                if (b % 2 == 0){
                    sum += b;
                }
                b = b + a;
                a = b - a;    
            }
            
            return sum;
        }
    }
}